### ISSUE TITLE
Use XDG compliant caching folder

### ISSUE THREAD

**Issue by dakra** [clojure-emacs/enrich-classpath#47]
Instead of littering the users home dir, I would prefer if it follows
 [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and put `.enrich-classpath-cache` in `$XDG_DATA_HOME` (`~/.local/share`) or maybe `$XDG_CACHE` (`~/.cache`).

**Comment by vemv** [comment]
Thanks!

`$XDG_CACHE_HOME` appears to make the most sense.

I'm curious, do you have that specific env var set?

**Comment by dakra** [comment]
> I'm curious, do you have that specific env var set?

No, I just use the default value, which for cache would point to `~/.cache`.

Maybe you can look at [babashka.fs](https://github.com/babashka/fs/blob/master/src/babashka/fs.cljc#L1216-L1274) for inspiration.

**Comment by vemv** [comment]
Thanks!

**Comment by vemv** [comment]
CIDER `20230912.1201` / `master` bundles this fix.

Cheers - V
