### ISSUE TITLE
Is jvm-opts in aliases not supported?

### ISSUE THREAD

**Issue by markx** [clojure-emacs/enrich-classpath#56]
Hi,

I tried the makefile and using `DEPS_MAIN_OPTS` to specify an alias that configures jvm-opts, something like `:jvm-opts ["-XstartOnFirstThread"]`.

After running `make` I inspected the `.enrich-classpath-deps-repl` file and the `-XstartOnFirstThread` was missing.

--- 
Looks like this works correctly for lein, so it's only an issue for tools.deps.

**Comment by vemv** [comment]
Enrich 1.18.4 should be available within an hour, and will also be included in CIDER within two hours.

If you're using Makefiles, it's enough to bump manually: https://github.com/clojure-emacs/enrich-classpath/blob/92bc201fd19bb4adbcec73637fca0c685a6844e3/examples/Makefile#L33C1-L33C1

Thanks for the report!

Cheers - V
