### ISSUE TITLE
lein: support customize main namespace (the -m param)? 

### ISSUE THREAD

**Issue by markx** [clojure-emacs/enrich-classpath#57]
It seems that in `.enrich-classpath-lein-repl` currently `-m nrepl.cmdline` is always used.

Is there a way to customize this? 

This is needed for e.g. games, when the app needs to run on the first thread (combined with `-J-XstartOnFirstThread`, maybe only relevant to macos). Starting the app from nrepl doesn't work.

**Comment by vemv** [comment]
Yes, we have https://github.com/clojure-emacs/enrich-classpath#main

Thanks for using Enrich and for today's other issue, I'll try to repro it asap.

Cheers - V
