### ISSUE TITLE
First alpha

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/enrich-classpath#6]
After importing, renaming, CI-ing etc this project this seems ready for an alpha. That would be useful for gathering some internal feedback.

@bbatsov , could you help me with that? I'm unfamiliar with releasing at clojure-emacs at all

**Comment by bbatsov** [comment]
Sure!

**Comment by bbatsov** [comment]
I've noticed the version now is 1.3.0. Should we make it 1.0.0-alpha1 or something like this?

**Comment by vemv** [comment]
1.4.0-alpha1 would be fine (this way I can compare it to its https://clojars.org/threatgrid/resolve-java-sources-and-javadocs predecessor)

Thanks!

**Comment by bbatsov** [comment]
Seems I'll have to deal with some paperwork first https://github.com/clojars/administration/issues/108

**Comment by bbatsov** [comment]
I'll be without a computer next week, so if they don't verify the new group ids today, this will have to wait a bit.

**Comment by bbatsov** [comment]
In the interest of shipping I just updated the group id to `mx.cider`, which is what clojars wants us to be using going forward. The first alpha is out!

**Comment by vemv** [comment]
@bbatsov: Thanks! Could I be added to the relevant Clojars group? (`vemv`)

Being able to deploy this one lib (vs others from mx.cider) would suffice.

**Comment by bbatsov** [comment]
Done.

**Comment by vemv** [comment]
⚡️
